"""Docket: file-protocol coordination for a planner/orchestrator/implementor agent pipeline.

The CLI is this stdlib-only package, one module per region of the ARCHITECTURE.md code
map. A module imports only from modules listed before it in `MODULES`, so that order
is also the dependency order, and a name is defined in exactly one module.
`bin/docket` is the entry point: it imports this package and calls `main`.
"""

from __future__ import annotations

from . import (
    common,
    frontmatter,
    paths,
    publication,
    policy,
    evidence,
    roots,
    baselines,
    bundles,
    locks,
    state,
    profiles,
    dependencies,
    freeze,
    aggregates,
    verification,
    templates,
    feedback,
    sessions,
    models,
    liveness,
    five_role,
    batches,
    events,
    delivery,
    signalling,
    health,
    gate,
    submission,
    amendments,
    transitions,
    verifier,
    qualification,
    doctor,
    playbooks,
    prompts,
    improvements,
    suite,
    metrics,
    release,
    packets,
    dispatch,
    commands,
    cli,
)
from .cli import main

MODULES = (
    common,
    frontmatter,
    paths,
    publication,
    policy,
    evidence,
    roots,
    baselines,
    bundles,
    locks,
    state,
    profiles,
    dependencies,
    freeze,
    aggregates,
    verification,
    templates,
    feedback,
    sessions,
    models,
    liveness,
    five_role,
    batches,
    events,
    delivery,
    signalling,
    health,
    gate,
    submission,
    amendments,
    transitions,
    verifier,
    qualification,
    doctor,
    playbooks,
    prompts,
    improvements,
    suite,
    metrics,
    release,
    packets,
    dispatch,
    commands,
    cli,
)
